name: Quality Assurance

on: [push, pull_request]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Run Grum
        run: vendor/bin/grumphp run

      - name: PHPUnit report
        run: ./vendor/bin/phpunit --log-junit report.xml
